# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07d8c5a4a1aff23820bf932155a419a08ef7e86588763c5e30b12d09105e80ce77954cee9983e7da0eed2fb661d614f4c5c01044c0e997009fcb584e456d3501

test:
  secret_key_base: 2e4c7ae9e1aeefe2ba5d9270d33a23ab4278d0abaeb669dfb3ee7f7146b102d940bc2403a9128cd04dadb068419e15d89f356858a7894e916fb8b730f0dd1ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
